name: sistema_equipamento
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.2
  intl: ^0.20.1
  path: ^1.8.3
  barcode: ^2.1.0
  simple_barcode_scanner: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/jagua_logo.png

